name: FinnouTools
version: '${project.version}'
main: fr.lordfinn.finnoutools.FinnouTools
api-version: 1.19
commands:
  brushToPattern:
    description: Apply your current WorldEdit brush to all matching blocks within the selected region and pattern
    usage: /brushToPattern
  giveInvisibleFrame:
    description: Gives the player an invisible item frame.
    usage: /giveInvisibleFrame